/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia.dos.pantalla;

import guia.dos.Cuenta;
import guia.dos.GuiaDos;
import java.awt.Color;
import javax.swing.ButtonModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Matias
 */
public class CrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCta = new javax.swing.ButtonGroup();
        jPanelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jRadioButtonCtaVacia = new javax.swing.JRadioButton();
        jLabelErrorMonto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonCtaInic = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMontoInic = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabelErrorMontoX = new javax.swing.JLabel();
        jLabelMontoCorrecto = new javax.swing.JLabel();

        buttonGroupCta.add(jRadioButtonCtaVacia);
        buttonGroupCta.add(jRadioButtonCtaInic);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Cuenta");
        setResizable(false);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(48, 48, 48));
        jLabel1.setText("Bienvenido, para continuar cree una cuenta");
        jPanelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 400, 50));

        jButtonAceptar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonAceptar.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jButtonAceptar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonAceptar.setBorderPainted(false);
        jButtonAceptar.setFocusPainted(false);
        jButtonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAceptarMouseExited(evt);
            }
        });
        jPanelFondo.add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 130, 30));

        jRadioButtonCtaVacia.setBackground(new java.awt.Color(153, 153, 153));
        jRadioButtonCtaVacia.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        jRadioButtonCtaVacia.setContentAreaFilled(false);
        jRadioButtonCtaVacia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonCtaVaciaMouseClicked(evt);
            }
        });
        jPanelFondo.add(jRadioButtonCtaVacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 254, 30, -1));

        jLabelErrorMonto.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jLabelErrorMonto.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorMonto.setText("Monto ingresado incorrecto");
        jPanelFondo.add(jLabelErrorMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 395, 160, 30));
        jLabelErrorMonto.setVisible(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/dos/iconos/iconoBanco2.png"))); // NOI18N
        jPanelFondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 190, 170));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Cuenta vacía");
        jPanelFondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 248, 140, 30));

        jRadioButtonCtaInic.setBackground(new java.awt.Color(153, 153, 153));
        jRadioButtonCtaInic.setContentAreaFilled(false);
        jRadioButtonCtaInic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonCtaInicMouseClicked(evt);
            }
        });
        jPanelFondo.add(jRadioButtonCtaInic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 334, 30, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Cuenta inicial");
        jPanelFondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 328, 140, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Crear una cuenta con un monto (múltiplo de diez) inicial");
        jPanelFondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 320, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/dos/iconos/4229863-24.png"))); // NOI18N
        jPanelFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 395, 30, 30));

        jTextFieldMontoInic.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldMontoInic.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jTextFieldMontoInic.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldMontoInic.setText("MONTO");
        jTextFieldMontoInic.setBorder(null);
        jTextFieldMontoInic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldMontoInicFocusGained(evt);
            }
        });
        jTextFieldMontoInic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldMontoInicKeyReleased(evt);
            }
        });
        jPanelFondo.add(jTextFieldMontoInic, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 400, 60, 20));
        jTextFieldMontoInic.setEnabled(false);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(60, 63, 65));
        jPanelFondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 340, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(60, 63, 65));
        jPanelFondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 422, 60, 10));

        jButtonSalir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/dos/iconos/iconfinder_basics-17_296817.png"))); // NOI18N
        jButtonSalir.setToolTipText("Salir");
        jButtonSalir.setBorder(null);
        jButtonSalir.setBorderPainted(false);
        jButtonSalir.setFocusPainted(false);
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseExited(evt);
            }
        });
        jPanelFondo.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 50, 50));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Crear una cuenta sin fondos");
        jPanelFondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 270, 30));

        jLabelErrorMontoX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/dos/iconos/2561211-24.png"))); // NOI18N
        jPanelFondo.add(jLabelErrorMontoX, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 395, 30, 30));
        jLabelErrorMontoX.setVisible(false);

        jLabelMontoCorrecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/dos/iconos/1031542-24.png"))); // NOI18N
        jPanelFondo.add(jLabelMontoCorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 395, 30, 30));
        jLabelErrorMontoX.setVisible(false);
        jLabelMontoCorrecto.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAceptarMouseEntered
        resaltarBotones(jButtonAceptar, new Color(53, 53, 53));

    }//GEN-LAST:event_jButtonAceptarMouseEntered

    private void jButtonAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAceptarMouseExited
        desresaltarBotones(jButtonAceptar, new Color(102, 102, 102));
    }//GEN-LAST:event_jButtonAceptarMouseExited

    private void jButtonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseEntered
        resaltarBotones(jButtonSalir, new Color(129,30,30));
    }//GEN-LAST:event_jButtonSalirMouseEntered

    private void jButtonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseExited
        desresaltarBotones(jButtonSalir, new Color(255, 255, 255));
    }//GEN-LAST:event_jButtonSalirMouseExited

    private void jRadioButtonCtaInicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonCtaInicMouseClicked
        jTextFieldMontoInic.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonCtaInicMouseClicked

    private void jRadioButtonCtaVaciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonCtaVaciaMouseClicked
        jTextFieldMontoInic.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonCtaVaciaMouseClicked

    private void jButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirMouseClicked

    private void jButtonAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAceptarMouseClicked

        boolean correcto = false;

        if (jRadioButtonCtaVacia.isSelected()) {

            cuenta = new Cuenta();
            correcto = true;

        } else if (Float.parseFloat(jTextFieldMontoInic.getText()) <= 0) {

            JOptionPane.showMessageDialog(null, "Error con el monto", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else {

            cuenta = new Cuenta(Float.parseFloat(jTextFieldMontoInic.getText()));
            correcto = true;

        }

        if (correcto) {
            JOptionPane.showMessageDialog(null, "Cuenta creada con éxito", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            Operacion marco = new Operacion();
            this.setVisible(false);
            marco.setVisible(true);
        }
    }//GEN-LAST:event_jButtonAceptarMouseClicked

    private void jTextFieldMontoInicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMontoInicKeyReleased
        mostrarLabelAviso(jTextFieldMontoInic, jLabelErrorMontoX, jLabelMontoCorrecto, jLabelErrorMonto);
    }//GEN-LAST:event_jTextFieldMontoInicKeyReleased

    private void jTextFieldMontoInicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMontoInicFocusGained
        limpiarJtextField(jTextFieldMontoInic, "MONTO");
    }//GEN-LAST:event_jTextFieldMontoInicFocusGained

    protected static void resaltarBotones(JButton boton, Color color) {
        boton.setBackground(color);
    }

    protected static void desresaltarBotones(JButton boton, Color color) {
        boton.setBackground(color);
    }

    protected static void limpiarJtextField(JTextField jt, String textoInicial){
        if(jt.getText().equals(textoInicial)){
            jt.setText(" ");
        }
    }
    
    protected static void mostrarLabelAviso(JTextField jt, JLabel error, JLabel correcto, JLabel textoError){
        
        if ((Float.parseFloat(jt.getText()) <= 0) || (Float.parseFloat(jt.getText())%10 != 0)) {
            correcto.setVisible(false);
            textoError.setVisible(true);
            error.setVisible(true);
        } else {
            correcto.setVisible(true);
            textoError.setVisible(false);
            error.setVisible(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }

    protected static Cuenta cuenta;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCta;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelErrorMonto;
    private javax.swing.JLabel jLabelErrorMontoX;
    private javax.swing.JLabel jLabelMontoCorrecto;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JRadioButton jRadioButtonCtaInic;
    private javax.swing.JRadioButton jRadioButtonCtaVacia;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldMontoInic;
    // End of variables declaration//GEN-END:variables
}
