/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia.dos.pantalla;

import guia.dos.Cuenta;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Matias
 */
public class Operacion extends javax.swing.JFrame {

    /**
     * Creates new form Operacion
     * @param cuenta
     */
    public Operacion() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonExtraccion = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButtonDeposito = new javax.swing.JButton();
        jButtonSaldo = new javax.swing.JButton();
        jPanelOperacion = new javax.swing.JPanel();
        jLabelTituloOperacion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jButtonListo = new javax.swing.JButton();
        jTextFieldMonto = new javax.swing.JTextField();
        jLabelErrorMonto = new javax.swing.JLabel();
        jLabelErrorMontoX = new javax.swing.JLabel();
        jLabelMontoCorrecto = new javax.swing.JLabel();
        jPanelSaldo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelSaldo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operación");
        setResizable(false);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/dos/iconos/iconfinder_basics-17_296817.png"))); // NOI18N
        jButtonSalir.setToolTipText("Salir");
        jButtonSalir.setBorder(null);
        jButtonSalir.setBorderPainted(false);
        jButtonSalir.setFocusPainted(false);
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseExited(evt);
            }
        });
        jPanelFondo.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/dos/iconos/iconfinder_finance-money-dollar-35_4058022.png"))); // NOI18N
        jPanelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelFondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 20, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/dos/iconos/iconfinder_finance-money-dollar-03_4057997.png"))); // NOI18N
        jPanelFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 50, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/dos/iconos/iconfinder_finance-money-dollar-14_4058008.png"))); // NOI18N
        jPanelFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 50, -1));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jPanelFondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 400, 20));

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelFondo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 20, 20));

        jButtonExtraccion.setBackground(new java.awt.Color(109, 109, 109));
        jButtonExtraccion.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 22)); // NOI18N
        jButtonExtraccion.setForeground(new java.awt.Color(33, 33, 33));
        jButtonExtraccion.setText("Extracción");
        jButtonExtraccion.setBorder(null);
        jButtonExtraccion.setBorderPainted(false);
        jButtonExtraccion.setFocusPainted(false);
        jButtonExtraccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExtraccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonExtraccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonExtraccionMouseExited(evt);
            }
        });
        jPanelFondo.add(jButtonExtraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 110, 40));
        jPanelFondo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 20, 10));

        jButtonDeposito.setBackground(new java.awt.Color(109, 109, 109));
        jButtonDeposito.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 22)); // NOI18N
        jButtonDeposito.setForeground(new java.awt.Color(33, 33, 33));
        jButtonDeposito.setText("Depósito");
        jButtonDeposito.setBorder(null);
        jButtonDeposito.setBorderPainted(false);
        jButtonDeposito.setFocusPainted(false);
        jButtonDeposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDepositoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDepositoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDepositoMouseExited(evt);
            }
        });
        jPanelFondo.add(jButtonDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 100, 40));

        jButtonSaldo.setBackground(new java.awt.Color(109, 109, 109));
        jButtonSaldo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 22)); // NOI18N
        jButtonSaldo.setForeground(new java.awt.Color(33, 33, 33));
        jButtonSaldo.setText("Saldo");
        jButtonSaldo.setBorder(null);
        jButtonSaldo.setBorderPainted(false);
        jButtonSaldo.setFocusPainted(false);
        jButtonSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSaldoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSaldoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSaldoMouseExited(evt);
            }
        });
        jPanelFondo.add(jButtonSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 100, 40));

        jPanelOperacion.setBackground(new java.awt.Color(199, 201, 203));
        jPanelOperacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTituloOperacion.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 22)); // NOI18N
        jLabelTituloOperacion.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTituloOperacion.setText("Ingrese el monto que desea depositar");
        jPanelOperacion.add(jLabelTituloOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Recuerde que el monto debe ser múltiplo de 10 (diez)");
        jPanelOperacion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator6.setForeground(new java.awt.Color(102, 102, 102));
        jPanelOperacion.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 90, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/dos/iconos/4229863-24.png"))); // NOI18N
        jPanelOperacion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, 33));

        jButtonListo.setBackground(new java.awt.Color(109, 109, 109));
        jButtonListo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 22)); // NOI18N
        jButtonListo.setForeground(new java.awt.Color(33, 33, 33));
        jButtonListo.setText("Listo");
        jButtonListo.setBorder(null);
        jButtonListo.setBorderPainted(false);
        jButtonListo.setFocusPainted(false);
        jButtonListo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonListoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonListoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonListoMouseExited(evt);
            }
        });
        jPanelOperacion.add(jButtonListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 90, 30));

        jTextFieldMonto.setBackground(new java.awt.Color(199, 201, 203));
        jTextFieldMonto.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jTextFieldMonto.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldMonto.setText("MONTO");
        jTextFieldMonto.setBorder(null);
        jTextFieldMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldMontoFocusGained(evt);
            }
        });
        jTextFieldMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldMontoKeyReleased(evt);
            }
        });
        jPanelOperacion.add(jTextFieldMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 89, 90, 30));

        jLabelErrorMonto.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jLabelErrorMonto.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorMonto.setText("Monto incorrecto");
        jPanelOperacion.add(jLabelErrorMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 100, 30));
        jLabelErrorMonto.setVisible(false);

        jLabelErrorMontoX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/dos/iconos/2561211-24.png"))); // NOI18N
        jPanelOperacion.add(jLabelErrorMontoX, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 30, 30));
        jLabelErrorMontoX.setVisible(false);

        jLabelMontoCorrecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/dos/iconos/1031542-24.png"))); // NOI18N
        jPanelOperacion.add(jLabelMontoCorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 30, 30));
        jLabelErrorMontoX.setVisible(false);
        jLabelMontoCorrecto.setVisible(false);

        jPanelFondo.add(jPanelOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 400, 170));
        jPanelFondo.remove(jPanelOperacion);

        jPanelSaldo.setBackground(new java.awt.Color(199, 201, 203));
        jPanelSaldo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("AR$");
        jPanelSaldo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 75, 50, 33));

        jLabelSaldo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelSaldo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 24)); // NOI18N
        jLabelSaldo.setForeground(new java.awt.Color(0, 0, 0));
        jPanelSaldo.add(jLabelSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 120, 33));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/dos/iconos/4229863-24.png"))); // NOI18N
        jPanelSaldo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 75, -1, 33));

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        jPanelSaldo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 104, 120, 20));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("El saldo de su cuenta es:");
        jPanelSaldo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 17, 284, 33));

        jPanelFondo.add(jPanelSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 400, 170));
        jPanelFondo.remove(jPanelSaldo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaldoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaldoMouseEntered
        CrearCuenta.resaltarBotones(jButtonSaldo, new Color(53,53,53));
    }//GEN-LAST:event_jButtonSaldoMouseEntered

    private void jButtonSaldoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaldoMouseExited
        CrearCuenta.desresaltarBotones(jButtonSaldo, new Color(109,109,109));
    }//GEN-LAST:event_jButtonSaldoMouseExited

    private void jButtonDepositoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDepositoMouseEntered
        CrearCuenta.resaltarBotones(jButtonDeposito, new Color(53,53,53));
    }//GEN-LAST:event_jButtonDepositoMouseEntered

    private void jButtonDepositoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDepositoMouseExited
        CrearCuenta.desresaltarBotones(jButtonDeposito, new Color(109,109,109));
    }//GEN-LAST:event_jButtonDepositoMouseExited

    private void jButtonExtraccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExtraccionMouseEntered
        CrearCuenta.resaltarBotones(jButtonExtraccion, new Color(53,53,53));
    }//GEN-LAST:event_jButtonExtraccionMouseEntered

    private void jButtonExtraccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExtraccionMouseExited
        CrearCuenta.desresaltarBotones(jButtonExtraccion, new Color(109,109,109));
    }//GEN-LAST:event_jButtonExtraccionMouseExited

    private void jButtonListoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonListoMouseEntered
        CrearCuenta.resaltarBotones(jButtonListo, new Color(53,53,53));
    }//GEN-LAST:event_jButtonListoMouseEntered

    private void jButtonListoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonListoMouseExited
        CrearCuenta.desresaltarBotones(jButtonListo, new Color(109,109,109));
    }//GEN-LAST:event_jButtonListoMouseExited

    private void jButtonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseEntered
        CrearCuenta.resaltarBotones(jButtonSalir, new Color(129,30,30));
    }//GEN-LAST:event_jButtonSalirMouseEntered

    private void jButtonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseExited
        CrearCuenta.desresaltarBotones(jButtonSalir, new Color(109,109,109));
    }//GEN-LAST:event_jButtonSalirMouseExited

    private void jButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseClicked
        System.exit(1);
    }//GEN-LAST:event_jButtonSalirMouseClicked

    private void jButtonSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaldoMouseClicked
        jPanelFondo.remove(jPanelOperacion);
        jPanelFondo.add(jPanelSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 400, 170));
        jPanelFondo.repaint();
        jPanelFondo.revalidate();
        
        jLabelSaldo.setText(cuenta.getSaldo().toString());
    }//GEN-LAST:event_jButtonSaldoMouseClicked

    private void jButtonDepositoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDepositoMouseClicked
        agregarPanelOperacion(jPanelOperacion, "Ingrese el monto que desea depositar");
        tipoOperacion=1;
    }//GEN-LAST:event_jButtonDepositoMouseClicked

    private void jButtonExtraccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExtraccionMouseClicked
        agregarPanelOperacion(jPanelOperacion, "Ingrese el monto que desea extraer");
        tipoOperacion=2;
    }//GEN-LAST:event_jButtonExtraccionMouseClicked

    private void jButtonListoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonListoMouseClicked
       //Como el jPanel que pide el monto para deposito/extraccion es el mismo (lo único que cambia es el texto)
       //tuve que usar una variable tipoOperacion para diferenciarlas, ya que el boton "Listo" es el mismo para ambas
       
        if(tipoOperacion==1){
           cuenta.ingresarDinero(Float.parseFloat(jTextFieldMonto.getText()));
           JOptionPane.showMessageDialog(null, "Depósito con éxito", "Aviso", JOptionPane.INFORMATION_MESSAGE);
       }else{
           
           if(cuenta.comprobarExtraccion(Float.parseFloat(jTextFieldMonto.getText()))){
               JOptionPane.showMessageDialog(null, "Extracción con éxito", "Aviso", JOptionPane.INFORMATION_MESSAGE);
               cuenta.sacarDinero(Float.parseFloat(jTextFieldMonto.getText()));
           }else{
               JOptionPane.showMessageDialog(null, "No posee los fondos suficientes", "Error", JOptionPane.ERROR_MESSAGE);
           }
           
       }
    }//GEN-LAST:event_jButtonListoMouseClicked

    private void jTextFieldMontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMontoFocusGained
        CrearCuenta.limpiarJtextField(jTextFieldMonto, "MONTO");
    }//GEN-LAST:event_jTextFieldMontoFocusGained

    private void jTextFieldMontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMontoKeyReleased
       
        CrearCuenta.mostrarLabelAviso(jTextFieldMonto, jLabelErrorMontoX, jLabelMontoCorrecto, jLabelErrorMonto);
    }//GEN-LAST:event_jTextFieldMontoKeyReleased

    private void agregarPanelOperacion(JPanel panel, String s){
        jPanelFondo.remove(jPanelSaldo);
        jPanelFondo.add(jPanelOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 400, 170));
        jPanelFondo.repaint();
        jPanelFondo.revalidate();
        
        jLabelTituloOperacion.setText(s);
    }
  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operacion().setVisible(true);
            }
        });
    }
    private int tipoOperacion; //si es 1 es deposito, si es 2 extracción
    private Cuenta cuenta = CrearCuenta.cuenta;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeposito;
    private javax.swing.JButton jButtonExtraccion;
    private javax.swing.JButton jButtonListo;
    private javax.swing.JButton jButtonSaldo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelErrorMonto;
    private javax.swing.JLabel jLabelErrorMontoX;
    private javax.swing.JLabel jLabelMontoCorrecto;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelTituloOperacion;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelOperacion;
    private javax.swing.JPanel jPanelSaldo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextFieldMonto;
    // End of variables declaration//GEN-END:variables
}
